// react/src/components/TodoList.tsx
import { todoItem } from '../types/types';
import TodoItem from './TodoItem';

type Props = {
  todos: todoItem[];
  onRemove: (id: number) => void;
};

const TodoList = ({ todos, onRemove }: Props) => {
  return (
    <section>
      <ul>
        {todos.map((todo: todoItem) => (
          <TodoItem
            key={todo.id}
            id={todo.id}
            todo={todo.todo}
            onRemove={onRemove}
          />
        ))}
      </ul>
    </section>
  );
};

export default TodoList;

// vue/src/components/TodoList.vue
<template>
  <ul>
    <TodoItem
      v-for="todo in todos"
      :key="todo.id"
      :todo="todo"
      @remove-todo="removeTodo"
    />
  </ul>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { Todo } from '../types/types';
import TodoItem from './TodoItem.vue';

export default defineComponent({
  components: {
    TodoItem,
  },
  props: {
    todos: {
      type: Array as () => Todo[],
      required: true,
    },
  },
  emits: ['remove-todo'],
  methods: {
    removeTodo(todo: Todo) {
      this.$emit('remove-todo', todo);
    },
  },
});
</script>
