// react/src/components/TodoForm.tsx
import React, { useState } from 'react';

type FormProps = {
  onAdd: (text: string) => void;
};

const TodoForm = ({ onAdd }: FormProps) => {
  const [value, setValue] = useState<string>('');
  const onSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    onAdd(value);
    setValue('');
  };
  const onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setValue(event.target.value);
  };
  return (
    <form onSubmit={onSubmit}>
      <input type="text" value={value} onChange={onChange} />
      <button type="submit">Add To Do</button>
    </form>
  );
};

export default TodoForm;

// svelte/src/components/TodoForm.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  let newTodo = '';
  const dispatch = createEventDispatcher();

  function addTodo(e: Event) {
    e.preventDefault(); // 폼 기본 동작을 막습니다.
    if (!newTodo.trim()) return;
    dispatch('addTodo', {
      id: Date.now(),
      content: newTodo,
    });
    newTodo = '';
  }
</script>

<form on:submit="{addTodo}">
  <input type="text" bind:value="{newTodo}" />
  <button type="submit">Add</button>
</form>
