// vue/src/components/TodoForm.vue
//src/components/TodoInput.vue
<template>
  <form @submit.prevent="addTodo">
    <input type="text" v-model="newTodo" @keyup.enter="addTodo" />
    <button @click="addTodo">Add</button>
  </form>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { Todo } from '../types/types';

export default defineComponent({
  emits: ['add-todo'],
  setup(_, { emit }) {
    const newTodo = ref('');

    const addTodo = () => {
      if (!newTodo.value.trim()) return;
      const todo: Todo = {
        id: Date.now(),
        todo: newTodo.value,
      };
      newTodo.value = '';
      emit('add-todo', todo);
    };

    return { newTodo, addTodo };
  },
});
</script>

// svelte/src/components/TodoForm.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  let newTodo = '';
  const dispatch = createEventDispatcher();

  function addTodo(e: Event) {
    e.preventDefault(); // 폼 기본 동작을 막습니다.
    if (!newTodo.trim()) return;
    dispatch('addTodo', {
      id: Date.now(),
      content: newTodo,
    });
    newTodo = '';
  }
</script>

<form on:submit="{addTodo}">
  <input type="text" bind:value="{newTodo}" />
  <button type="submit">Add</button>
</form>
