// vue/src/components/TodoItem.vue
<template>
  <article>
    <span>{{ todo.todo }}</span>
    <button @click="removeTodo">Delete</button>
  </article>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { Todo } from '../types/types';

export default defineComponent({
  props: {
    todo: {
      type: Object as () => Todo,
      required: true,
    },
  },
  emits: ['remove-todo'],
  methods: {
    removeTodo() {
      this.$emit('remove-todo', this.todo);
    },
  },
});
</script>

// svelte/src/components/TodoItem.svelte
<script lang="ts">
  export let todo: {
    id: number;
    content: string;
  };
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();

  function requestRemoveTodo() {
    dispatch('removeTodo', todo);
  }
</script>

<article>
  <span>{todo.content}</span>
  <button on:click="{requestRemoveTodo}">Delete</button>
</article>
